#include <stdint.h>
#include <float.h>
#include <stddef.h>

#include "rfStruct.h"

// First-hit rays /////////////////////////////////////////////////////////////

#define TRACEPIPELINE rfRays
#define TRACEPARAM    rfRayResults*
#define TRACEPARAMPASSBYREFERENCE (0)

#define TRACEHIT  rfHitFcn

// Set to non-zero to enable ray distance clipping : new clipdist parameter,
// TRACECLIP() is called
#define TRACEDISTCLIP (0)

// Set to non-zero if roots have to be resolved from scratch to match origin
#define TRACERESOLVEROOT (0)

// Set to non-zero if roots have to be displaced to match origin
#define TRACEDISPLACEROOT (0)

// Set to non-zero if roots were generated by quad tracing
#define TRACEQUADROOT (0)

// Do we want intersection points, barycentric coordinates, hit point
// distance, etc.?
#define TRACEHITMODELDATA  (0)
#define TRACEHITOBJECTDATA (0)
#define TRACEHITVECTOR     (0)
#define TRACEHITPOINT      (0)
#define TRACEHITUV         (1)
#define TRACEHITDATA       (1)
#define TRACEHITDIST       (1)
#define TRACEHITPLANE      (1)
#define TRACEHITSIDE       (0)
#define TRACEHITROOT       (0)
#define TRACEHITMATRIX     (0)

RF_INLINE void rfHitFcn(rfRayResults* rayData,
                        void*  modeldata,
                        void*  objectdata,
                        float* dir,
                        float* hitpt,
                        float* hituv,
                        void*  tridata,
                        float  hitdist,
                        float* n,
                        int    hitside,
                        rfRoot root,
                        float* matrix)
{
  rayData->hit     = 1;
  rayData->hitDist = hitdist;
  rayData->Ng[0]   = n[0];
  rayData->Ng[1]   = n[1];
  rayData->Ng[2]   = n[2];
  rayData->u       = hituv[0];
  rayData->v       = hituv[1];

  rfTriangleData *data = (rfTriangleData*)tridata;

  rayData->geomID  = data->geomID;
  rayData->primID  = data->primID;
}

// Assemble pipeline for primary rays
#include <RF/rftrace.h>
